---
title: "Topic Modeling for Open Comments"
author: "Clara Wiebel"
date: "2024-06-14"
output: html_document
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = F, warning = FALSE, message = FALSE) 
devtools::document()
rcmdcheck::rcmdcheck()
pkgdown::build_site(new_process = FALSE)
devtools::build()
# Before sourcing, consider setting this option (can increase 5000); 
#  without it the code may ran out of memory
options(java.parameters = "-Xmx5000m")
library(topics)
library(dplyr)

```


```{r data prep}
translate_q8 <- read.csv("translate_q8.csv")
# make an ID column for our df
translate_q8$id = c(1:nrow(translate_q8)) # n = 237
translate_q8$Agreement_num <- as.numeric(substr(translate_q8$Agreement, 1, 1))

```



```{r}

### Test package functionality ###

## --> Testing it on the example ofg


# 1) Preprocessing function --> this converts the data into a document term matrix (DTM) and removes stopwords, punctuation etc.
tm_dtm <- topicsDtm(data = translate_q8[["translation"]],
                 ngram_window = c(1,5))

```

```{r}
# 2) Model training --> trains the LDA model based on the DTM with predefined number of topics ant iterations
tm_model <- topicsModel(dtm = tm_dtm,
                    num_topics = 20,
                    num_iterations = 1000)

```
```{r}

# 3) Model inference --> use the trained LDA model to infer the topic term distribution of the documents
tm_preds <- topicsPreds(model = tm_model,
                    data = translate_q8[["translation"]])
```

```{r}

# 4) Statistical analysis --> analyze the relationship between the topics and a prediction variable with linear regression, binary regression, ridge regression or correlation
tm_test <- topicsTest(model = tm_model,
                   data = translate_q8,
                   preds = tm_preds,
                   pred_var = "Agreement_num")
```


# 5) Visualization --> Create wordclouds of statistically significant topics


```








